language: php

php:
    - 7.0

sudo: required

#script:

#    - ./build/tools/phpunit.phar --configuration ./build/travis-ci.xml
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
install:
  - composer update

script: phpunit --bootstrap vendor/autoload.php
notifications:
  email: false